"""baseline nimbus schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settlement_date', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_subtype', sa.String(length=50), nullable=True),
    sa.Column('source_lineage', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('signed_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('register_id', sa.String(length=50), nullable=True),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('tender_type', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('settlement_reference', sa.String(length=255), nullable=True),
    sa.Column('reconciliation_status', sa.String(length=50), nullable=False),
    sa.Column('disposition', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_transactions_business_date'), 'canonical_transactions', ['business_date'], unique=False)
    op.create_index(op.f('ix_canonical_transactions_payment_reference'), 'canonical_transactions', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_canonical_transactions_reconciliation_status'), 'canonical_transactions', ['reconciliation_status'], unique=False)
    op.create_index(op.f('ix_canonical_transactions_store_id'), 'canonical_transactions', ['store_id'], unique=False)
    op.create_index(op.f('ix_canonical_transactions_transaction_date'), 'canonical_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_canonical_transactions_transaction_type'), 'canonical_transactions', ['transaction_type'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('total_exception_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_exposure', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('investigation_status', sa.String(length=50), nullable=False),
    sa.Column('evidence_completeness', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_business_date'), 'cases', ['business_date'], unique=False)
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_store_id'), 'cases', ['store_id'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('source_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('source_version', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quarantine_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_records_delivery_id'), 'source_records', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_source_records_received_at'), 'source_records', ['received_at'], unique=False)
    op.create_index(op.f('ix_source_records_source_record_id'), 'source_records', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_source_records_source_system'), 'source_records', ['source_system'], unique=False)
    op.create_index(op.f('ix_source_records_status'), 'source_records', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_object_id'), 'audit_events', ['object_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('exception_type', sa.String(length=100), nullable=False),
    sa.Column('exception_family', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('detection_origin', sa.String(length=50), nullable=False),
    sa.Column('detection_rule_id', sa.String(length=100), nullable=False),
    sa.Column('exception_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('estimated_exposure', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('close_impact', sa.String(length=20), nullable=False),
    sa.Column('close_blocker_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_case_id'), 'exceptions', ['case_id'], unique=False)
    op.create_index(op.f('ix_exceptions_exception_type'), 'exceptions', ['exception_type'], unique=False)
    op.create_index(op.f('ix_exceptions_status'), 'exceptions', ['status'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('finding_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('supporting_rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_case_id'), 'findings', ['case_id'], unique=False)
    op.create_index(op.f('ix_findings_investigation_id'), 'findings', ['investigation_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('disposition_type', sa.String(length=50), nullable=False),
    sa.Column('action_class', sa.String(length=50), nullable=False),
    sa.Column('expected_workflow', sa.Text(), nullable=False),
    sa.Column('financial_impact', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_case_id'), 'recommendations', ['case_id'], unique=False)
    op.create_index(op.f('ix_recommendations_investigation_id'), 'recommendations', ['investigation_id'], unique=False)
    op.create_table('evidence_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('exception_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('evidence_status', sa.String(length=50), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('evidence_data', sa.JSON(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('staleness_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_snapshots_case_id'), 'evidence_snapshots', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_snapshots_exception_id'), 'evidence_snapshots', ['exception_id'], unique=False)
    op.create_table('human_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('decision_type', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('authority_check', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_decisions_case_id'), 'human_decisions', ['case_id'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_evaluations_case_id'), 'policy_evaluations', ['case_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_type', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('definition_version', sa.String(length=100), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_case_id'), 'workflows', ['case_id'], unique=False)
    op.create_table('validation_obligations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('expected_observation', sa.Text(), nullable=False),
    sa.Column('due_window_hours', sa.Integer(), nullable=False),
    sa.Column('verification_rule', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verification_result', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_obligations_case_id'), 'validation_obligations', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_obligations_case_id'), table_name='validation_obligations')
    op.drop_table('validation_obligations')
    op.drop_index(op.f('ix_workflows_case_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_policy_evaluations_case_id'), table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_index(op.f('ix_human_decisions_case_id'), table_name='human_decisions')
    op.drop_table('human_decisions')
    op.drop_index(op.f('ix_evidence_snapshots_exception_id'), table_name='evidence_snapshots')
    op.drop_index(op.f('ix_evidence_snapshots_case_id'), table_name='evidence_snapshots')
    op.drop_table('evidence_snapshots')
    op.drop_index(op.f('ix_recommendations_investigation_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_case_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_findings_investigation_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_case_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_exceptions_status'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_exception_type'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_case_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_audit_events_object_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_source_records_status'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_source_system'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_source_record_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_received_at'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_delivery_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_cases_store_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_business_date'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_canonical_transactions_transaction_type'), table_name='canonical_transactions')
    op.drop_index(op.f('ix_canonical_transactions_transaction_date'), table_name='canonical_transactions')
    op.drop_index(op.f('ix_canonical_transactions_store_id'), table_name='canonical_transactions')
    op.drop_index(op.f('ix_canonical_transactions_reconciliation_status'), table_name='canonical_transactions')
    op.drop_index(op.f('ix_canonical_transactions_payment_reference'), table_name='canonical_transactions')
    op.drop_index(op.f('ix_canonical_transactions_business_date'), table_name='canonical_transactions')
    op.drop_table('canonical_transactions')
    # ### end Alembic commands ###
