"""canonical transaction source link

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canonical_transactions', sa.Column('source_record_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_canonical_transactions_source_record_id'), 'canonical_transactions', ['source_record_id'], unique=False)
    op.create_foreign_key('fk_canonical_transactions_source_record_id', 'canonical_transactions', 'source_records', ['source_record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_canonical_transactions_source_record_id', 'canonical_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_canonical_transactions_source_record_id'), table_name='canonical_transactions')
    op.drop_column('canonical_transactions', 'source_record_id')
    # ### end Alembic commands ###
