"""case work management batch runs and indexes

Revision ID: 0003
Revises: 0002
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_counts', sa.JSON(), nullable=True),
    sa.Column('transactions_loaded', sa.Integer(), nullable=False),
    sa.Column('matched_pairs', sa.Integer(), nullable=False),
    sa.Column('cases_created', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_runs_business_date'), 'batch_runs', ['business_date'], unique=False)
    op.create_index(op.f('ix_batch_runs_started_at'), 'batch_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_batch_runs_status'), 'batch_runs', ['status'], unique=False)
    op.add_column('cases', sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cases', sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True))
    op.execute("""UPDATE cases SET sla_due_at = created_at + CASE priority
        WHEN 'Critical' THEN interval '4 hours' WHEN 'High' THEN interval '24 hours' ELSE interval '72 hours' END""")
    op.create_index(op.f('ix_cases_assigned_to'), 'cases', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index('ix_cases_status_exposure', 'cases', ['status', 'total_exposure'], unique=False)
    op.create_index('ix_cases_status_sla', 'cases', ['status', 'sla_due_at'], unique=False)
    op.create_index('ix_cases_type_store', 'cases', ['case_type', 'store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cases_type_store', table_name='cases')
    op.drop_index('ix_cases_status_sla', table_name='cases')
    op.drop_index('ix_cases_status_exposure', table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_to'), table_name='cases')
    op.drop_column('cases', 'snoozed_until')
    op.drop_column('cases', 'sla_due_at')
    op.drop_index(op.f('ix_batch_runs_status'), table_name='batch_runs')
    op.drop_index(op.f('ix_batch_runs_started_at'), table_name='batch_runs')
    op.drop_index(op.f('ix_batch_runs_business_date'), table_name='batch_runs')
    op.drop_table('batch_runs')
    # ### end Alembic commands ###
