"""audit hash chain and exports

Revision ID: 0004
Revises: 0003
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_destinations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('export_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('dataset', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('audit_head_hash', sa.String(length=64), nullable=True),
    sa.Column('range_from', sa.Integer(), nullable=True),
    sa.Column('range_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_ref', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['export_destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_export_batches_created_at'), 'export_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_export_batches_dataset'), 'export_batches', ['dataset'], unique=False)
    op.create_index(op.f('ix_export_batches_destination_id'), 'export_batches', ['destination_id'], unique=False)
    op.create_index(op.f('ix_export_batches_status'), 'export_batches', ['status'], unique=False)
    op.create_table('export_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('destination_id', sa.String(length=36), nullable=False),
    sa.Column('dataset', sa.String(length=30), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('object_version', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['export_batches.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['export_destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'dataset', 'object_id', 'object_version', name='uq_export_item')
    )
    op.create_index(op.f('ix_export_items_batch_id'), 'export_items', ['batch_id'], unique=False)
    op.add_column('audit_events', sa.Column('seq', sa.Integer(), nullable=True))
    op.add_column('audit_events', sa.Column('prev_hash', sa.String(length=64), nullable=True))
    op.add_column('audit_events', sa.Column('hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_audit_events_seq', 'audit_events', ['seq'])

    # --- tamper-evident, append-only audit trail (enforced in the database) ---
    op.execute("CREATE SEQUENCE IF NOT EXISTS audit_events_seq")
    op.execute("""
    CREATE OR REPLACE FUNCTION audit_event_hash(prev text, e audit_events) RETURNS text AS $$
        SELECT encode(sha256(convert_to(concat_ws('|', coalesce(prev, 'GENESIS'), e.seq::text, e.id, e.event_type, e.actor,
            e.object_type, e.object_id, coalesce(e.case_id, ''), e.action_description,
            coalesce(e.before_state::text, ''), coalesce(e.after_state::text, ''),
            to_char(e.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US')), 'UTF8')), 'hex')
    $$ LANGUAGE sql IMMUTABLE
    """)
    op.execute("""
    DO $$
    DECLARE r audit_events; prev text := NULL; n bigint := 0; h text;
    BEGIN
        FOR r IN SELECT * FROM audit_events ORDER BY created_at, id LOOP
            n := nextval('audit_events_seq');
            r.seq := n;
            h := audit_event_hash(prev, r);
            UPDATE audit_events SET seq = n, prev_hash = prev, hash = h WHERE id = r.id;
            prev := h;
        END LOOP;
    END $$
    """)
    op.execute("""
    CREATE OR REPLACE FUNCTION audit_events_before_insert() RETURNS trigger AS $$
    DECLARE prev text;
    BEGIN
        PERFORM pg_advisory_xact_lock(727001);
        NEW.seq := nextval('audit_events_seq');
        SELECT hash INTO prev FROM audit_events ORDER BY seq DESC LIMIT 1;
        NEW.prev_hash := prev;
        NEW.hash := audit_event_hash(prev, NEW);
        RETURN NEW;
    END $$ LANGUAGE plpgsql
    """)
    op.execute("CREATE TRIGGER audit_chain BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION audit_events_before_insert()")
    op.execute("""
    CREATE OR REPLACE FUNCTION audit_events_immutable() RETURNS trigger AS $$
    BEGIN RAISE EXCEPTION 'audit_events is append-only'; END $$ LANGUAGE plpgsql
    """)
    op.execute("CREATE TRIGGER audit_no_change BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION audit_events_immutable()")
    op.execute("CREATE TRIGGER audit_no_truncate BEFORE TRUNCATE ON audit_events FOR EACH STATEMENT EXECUTE FUNCTION audit_events_immutable()")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_no_truncate ON audit_events")
    op.execute("DROP TRIGGER IF EXISTS audit_no_change ON audit_events")
    op.execute("DROP TRIGGER IF EXISTS audit_chain ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS audit_events_immutable()")
    op.execute("DROP FUNCTION IF EXISTS audit_events_before_insert()")
    op.execute("DROP FUNCTION IF EXISTS audit_event_hash(text, audit_events)")
    op.execute("DROP SEQUENCE IF EXISTS audit_events_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_audit_events_seq', 'audit_events', type_='unique')
    op.drop_column('audit_events', 'hash')
    op.drop_column('audit_events', 'prev_hash')
    op.drop_column('audit_events', 'seq')
    op.drop_index(op.f('ix_export_items_batch_id'), table_name='export_items')
    op.drop_table('export_items')
    op.drop_index(op.f('ix_export_batches_status'), table_name='export_batches')
    op.drop_index(op.f('ix_export_batches_destination_id'), table_name='export_batches')
    op.drop_index(op.f('ix_export_batches_dataset'), table_name='export_batches')
    op.drop_index(op.f('ix_export_batches_created_at'), table_name='export_batches')
    op.drop_table('export_batches')
    op.drop_table('export_destinations')
    # ### end Alembic commands ###
